project:
  type: website
  output-dir: docs

website:
  title: "nadia-irdina.github.io"
  back-to-top-navigation: true
  navbar:
    background: "#68552D"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: DataStory.qmd
        text: Data Story
      - href: insights.qmd
        text: Insights
      - href: Conclusion.qmd
        text: Conclusion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: "#68552D"

editor: visual

